version: '3'
services:
  notizendb:
    image: "postgres"
    restart: always
    env_file:
      - database.env
#     volumes:
#       - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
# volumes:
#   database-data: # named volumes can be managed easier using docker-compose
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080